# Generated by Django 4.2.4 on 2023-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user1',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user1',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='username',
        ),
        migrations.AlterField(
            model_name='user1',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user1',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user1',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
